### ISSUE TITLE
Attempting to enable  `nixos-cli` leads to an error, due to the module trying to evaluate the entire Nixpkgs

### ISSUE THREAD

**Issue by Nanotwerp** [nix-community/nixos-cli#41]
### What Happened?

[Here's](https://gist.github.com/Nanotwerp/144044369c2308b3935a8eee9e7d825e) the gist of the error. I'm not sure if this is some issue with my config, or if the `module.nix` is doing something recursively wonky.

### How To Reproduce

Try to enable `nixos-cli` by adding following the flake instructions and adding 
```ocaml
 services.nixos-cli = {
    enable = true;
    package = inputs.nixos-cli.packages.${pkgs.stdenv.hostPlatform.system}.default;
  };
```

### Expected Behavior

I expected `nixos-cli` to be enabled.

### Features

```shell
nixos 0.12.0-dev

git rev: 7b6f5712a2ab174fc81692bf607cb205d2837035
zig version: 0.13.0
optimisation mode: ReleaseSafe

Compilation Options
-------------------
flake           :: true
nixpkgs_version :: 24.05
```

**Comment by water-sucks** [comment]
The evaluation of all of `nixpkgs` is due to the `prebuildOptionCache` option being enabled by default. It actually does eval all available NixOS options.

If you set the following:
```nix
services.nixos-cli = {
  enable = true;
  prebuildOptionCache = false;
};
```

You should be able to disable it and it will eval much faster.

I'm trying to reproduce your issue, though, and can't seem to do so. I'll let you know if that changes.

Also FYI, if you're using a flake configuraton, you also don't need to use the `package` option, it's the default value for the option.

**Comment by Nanotwerp** [comment]
> The evaluation of all of `nixpkgs` is due to the `prebuildOptionCache` option being enabled by default. It actually does eval all available NixOS options.
> 
> If you set the following:
> 
> ```nix
> services.nixos-cli = {
>   enable = true;
>   prebuildOptionCache = false;
> };
> ```
> 
> You should be able to disable it and it will eval much faster.
> 
> I'm trying to reproduce your issue, though, and can't seem to do so. I'll let you know if that changes.
> 
> Also FYI, if you're using a flake configuraton, you also don't need to use the `package` option, it's the default value for the option.

Ah, I see! I'm on `nixos-unstable-small`, if that helps. It could also be due to me using [`Lix`](https://lix.systems/) instead of `Nix`, but I doubt this, since I also tried evaluating `nixos-cli` without `Lix`.

After taking your advice and disabling `prebuildOptionCache`, `nixos option`, I don't get the same issue, but there's a new issue of `nixos option` being unable to find the options cache:

```
❯ nixos option -i
info: building option list cache, please wait...
error: unable to find options cache; cannot continue
```

**Comment by water-sucks** [comment]
Upon reading your error trace, I found a wonderful little snippet that's quite easy to miss:

```nix
       … while calling the 'addErrorContext' builtin
         at /nix/store/mks1f1fqkxfk0xjxfnbk98lyf76mcf8m-source/lib/options.nix:345:13:
          344|           default =
          345|             builtins.addErrorContext "while evaluating the ${if opt?defaultText then "defaultText" else "default value"} of option `${name}`" (
             |             ^
          346|               renderOptionValue (opt.defaultText or opt.default)

       … while evaluating the default value of option `disko.imageBuilderPkgs`
```

Well, this seems to be the culprit. Are you using `disko`? I think something is going wonky with that, where it fails to evaluate the value, which is strange, since this value does work on options with type `pkgs` normally.

I will modify the Nix expressions used to generate the options cache such that failures like this will result in a ("unable to eval") text for that option only, though I don't know quite how long this will take, since I would need to either re-implement the generation of the option cache, or try and figure out some alternate solution to failing option evaluation. I'm working on this in my spare time, after all. I also need to improve some error reporting, such as the adding the Nix version and showing a proper trace for some commands.

Thanks so much for this error report!

**Comment by water-sucks** [comment]
Hmm, actually, as a temporary fix, can you upgrade `disko`?

I see https://github.com/nix-community/disko/pull/741 fixes this problem where the option in question does not evaluate properly.

You can probably remove the disabling of `prebuildOptionCache` once you upgrade `disko`. That'll make your startup time for the `option` subcommand much faster.

**Comment by Nanotwerp** [comment]
> Hmm, actually, as a temporary fix, can you upgrade `disko`?
> 
> I see [nix-community/disko#741](https://github.com/nix-community/disko/pull/741) fixes this problem where the option in question does not evaluate properly.
> 
> You can probably remove the disabling of `prebuildOptionCache` once you upgrade `disko`. That'll make your startup time for the `option` subcommand much faster.

Nice! Thank you! Updating `disko` did indeed fix the issue! I'm curious, though; how does `nixos option` build the option list cache without evaluating Nixpkgs?

**Comment by water-sucks** [comment]
> Nice! Thank you! Updating `disko` did indeed fix the issue! I'm curious, though; how does `nixos option` build the option list cache without evaluating Nixpkgs?

It does eval `nixpkgs`, sort of.

https://github.com/water-sucks/nixos/blob/7b6f5712a2ab174fc81692bf607cb205d2837035/src/option.zig#L146-L172

These are the Nix expressions that are evaluated to build the options cache. The module implementation of `prebuildOptionCache` has the same idea. I run though a couple of steps:

1. Check if `/run/current-system` has a file at `/etc/nixos-cli/options-cache.json`
2. If not, then attempt to build the linked Nix expression, and parse the resulting file that is printed to `stdout`.
3. Fail

That's basically it. I may change this in the future to support things like looking through HM options, but I'll need to think about this more before I take action on that.
